In [48]:
import pandas as pd

In [49]:
# Pandas Series
# Sabse pehle tumhari list ko Series mein convert karte hain:
data = [10, 20, 30, 40, 50]

series = pd.Series(data)

print(series)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [50]:
# Custom Index
# Ab apna index khud set karte hain
data = [10, 20, 30, 40, 50]

series = pd.Series(
    data,
    index=["A", "B", "C", "D", "E"]
)

print(series)

A    10
B    20
C    30
D    40
E    50
dtype: int64

In [51]:
age = [19,19,18,15,19]
series = pd.Series(
    age,
    index=["Abdullah", "Bilal", "uman", "hashim", "Esham "]
)

print(series)

Abdullah    19
Bilal       19
uman        18
hashim      15
Esham       19
dtype: int64

In [52]:
# 1. List se DataFrame
data = [
    ["Ali", "Lahore", 5000],
    ["Ahmed", "Karachi", 7000],
    ["Hamza", "Islamabad", 6000]
]

df = pd.DataFrame(
    data,
    columns=["Customer", "City", "Sales"]
)

print(df)

  Customer       City  Sales
0      Ali     Lahore   5000
1    Ahmed    Karachi   7000
2    Hamza  Islamabad   6000

In [53]:
data = [
    ["Ali", "Lahore", 5000],
    ["Ahmed", "Karachi", 7000],
    
]

df = pd.DataFrame(
    data,
    columns=["Customer", "City", "Sales"]
)

print(df)

  Customer     City  Sales
0      Ali   Lahore   5000
1    Ahmed  Karachi   7000

In [54]:
# data → list
# columns → column names
# pd.DataFrame() → list ko DataFrame mein convert karta hai
data = [
    ["Ali", "Lahore", 5000],
    ["Ahmed", "Karachi", 7000],
    ["Hamza", "Islamabad", 6000]
]

df = pd.DataFrame(
    data,
    columns=["Customer", "City", "Sales"]
)

print(df)

  Customer       City  Sales
0      Ali     Lahore   5000
1    Ahmed    Karachi   7000
2    Hamza  Islamabad   6000

In [55]:
# Dictionary se DataFrame
data = {
    "Customer": ["Ali", "Ahmed", "Hamza"],
    "City": ["Lahore", "Karachi", "Islamabad"],
    "Sales": [5000, 7000, 6000]
}

df = pd.DataFrame(data)

print(df)

  Customer       City  Sales
0      Ali     Lahore   5000
1    Ahmed    Karachi   7000
2    Hamza  Islamabad   6000

In [56]:
import pandas as pd
df = pd.read_csv("Online Retail.csv")

In [57]:
# head() → starting rows
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [58]:
# head() → ending rows
df.tail()
# last ki 10 row 
df.tail(10)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
541899,581587,22726,ALARM CLOCK BAKELIKE GREEN,4,2011-12-09 12:50:00,3.75,12680.0,France
541900,581587,22730,ALARM CLOCK BAKELIKE IVORY,4,2011-12-09 12:50:00,3.75,12680.0,France
541901,581587,22367,CHILDRENS APRON SPACEBOY DESIGN,8,2011-12-09 12:50:00,1.95,12680.0,France
541902,581587,22629,SPACEBOY LUNCH BOX,12,2011-12-09 12:50:00,1.95,12680.0,France
541903,581587,23256,CHILDRENS CUTLERY SPACEBOY,4,2011-12-09 12:50:00,4.15,12680.0,France
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France

In [59]:
# yeh row aur colum ki total quantity bataye ga
df.shape

(541909, 8)

In [60]:
rows = df.shape[0]
columns = df.shape[1]

print("Rows:", rows)
print("Columns:", columns)

Rows: 541909
Columns: 8

In [61]:
# yeh colum batata hai 
df.columns

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='str')

In [62]:
# is sa column ka nam pata lage ga
df.columns[0]

'InvoiceNo'

In [63]:
# create a name list of cloumns
df.columns.tolist()

['InvoiceNo',
 'StockCode',
 'Description',
 'Quantity',
 'InvoiceDate',
 'UnitPrice',
 'CustomerID',
 'Country']

In [64]:
# # info() kya batata hai?

# Isse humein pata chalta hai:

# Total entries / rows
# Har column ka naam
# Har column mein non-null values
# Missing values ka indication
# Har column ka data type
# DataFrame ki memory usage
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  str
 1   StockCode    541909 non-null  str
 2   Description  540455 non-null  str
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  str
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  str
dtypes: float64(2), int64(1), str(5)
memory usage: 69.3 MB

In [65]:
# yeh mean, madian, mode, sd, 25%, 50%,75%, max nikal deta hai 
df.describe()

            Quantity      UnitPrice     CustomerID
count  541909.000000  541909.000000  406829.000000
mean        9.552250       4.611114   15287.690570
std       218.081158      96.759853    1713.600303
min    -80995.000000  -11062.060000   12346.000000
25%         1.000000       1.250000   13953.000000
50%         3.000000       2.080000   15152.000000
75%        10.000000       4.130000   16791.000000
max     80995.000000   38970.000000   18287.000000

In [66]:
df.describe(include='object')

C:\Users\Administrator\AppData\Local\Temp\ipykernel_9440\87514550.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include='object')

,InvoiceNo,StockCode,Description,InvoiceDate,Country
count,541909,541909,540455,541909,541909
unique,25900,4070,4223,23260,38
top,573585,85123A,WHITE HANGING HEART T-LIGHT HOLDER,2011-10-31 14:41:00,United Kingdom
freq,1114,2313,2369,1114,495478

In [67]:
df.describe()

            Quantity      UnitPrice     CustomerID
count  541909.000000  541909.000000  406829.000000
mean        9.552250       4.611114   15287.690570
std       218.081158      96.759853    1713.600303
min    -80995.000000  -11062.060000   12346.000000
25%         1.000000       1.250000   13953.000000
50%         3.000000       2.080000   15152.000000
75%        10.000000       4.130000   16791.000000
max     80995.000000   38970.000000   18287.000000

In [68]:
# All columns ka mean etc
df.describe(include='all')

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
count,541909,541909,540455,541909.000000,541909,541909.000000,406829.000000,541909
unique,25900,4070,4223,NaN,23260,NaN,NaN,38
top,573585,85123A,WHITE HANGING HEART T-LIGHT HOLDER,NaN,2011-10-31 14:41:00,NaN,NaN,United Kingdom
freq,1114,2313,2369,NaN,1114,NaN,NaN,495478
mean,NaN,NaN,NaN,9.552250,NaN,4.611114,15287.690570,NaN
std,NaN,NaN,NaN,218.081158,NaN,96.759853,1713.600303,NaN
min,NaN,NaN,NaN,-80995.000000,NaN,-11062.060000,12346.000000,NaN
25%,NaN,NaN,NaN,1.000000,NaN,1.250000,13953.000000,NaN
50%,NaN,NaN,NaN,3.000000,NaN,2.080000,15152.000000,NaN
75%,NaN,NaN,NaN,10.000000,NaN,4.130000,16791.000000,NaN
max,NaN,NaN,NaN,80995.000000,NaN,38970.000000,18287.000000,NaN

In [69]:
# → Series = single column
df["Quantity"]

0          6
1          6
2          8
3          6
4          6
          ..
541904    12
541905     6
541906     4
541907     4
541908     3
Name: Quantity, Length: 541909, dtype: int64

In [70]:
# df ko variable ma store karna hai 
quantity = df["Quantity"]
quantity
# type print karana 
type(quantity)
# is ka first 5 value print karana 
quantity.head()
 # is ka last 5 value print karana 
quantity.tail()
# pehle 5 value ko sum karna 
quantity.sum()
# is ka mean nikalna
quantity.mean()
# is ka avaerge nikalna
quantity.min()
# is ka max nikalna 
quantity.max()
# sirf wo row print karo jo 100 sa greater hoo
df[df["Quantity"] > 100]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
96,536378,21212,PACK OF 72 RETROSPOT CAKE CASES,120,2010-12-01 09:37:00,0.42,14688.0,United Kingdom
178,536387,79321,CHILLI LIGHTS,192,2010-12-01 09:58:00,3.82,16029.0,United Kingdom
179,536387,22780,LIGHT GARLAND BUTTERFILES PINK,192,2010-12-01 09:58:00,3.37,16029.0,United Kingdom
180,536387,22779,WOODEN OWLS LIGHT GARLAND,192,2010-12-01 09:58:00,3.37,16029.0,United Kingdom
181,536387,22466,FAIRY TALE COTTAGE NIGHTLIGHT,432,2010-12-01 09:58:00,1.45,16029.0,United Kingdom
...,...,...,...,...,...,...,...,...
540442,581487,21137,BLACK RECORD COVER FRAME,120,2011-12-09 09:44:00,3.39,15694.0,United Kingdom
541286,581497,22355,CHARLOTTE BAG SUKI DESIGN,110,2011-12-09 10:23:00,2.46,NaN,United Kingdom
541545,581501,22319,HAIRCLIPS FORTIES FABRIC ASSORTED,180,2011-12-09 10:46:00,0.19,12985.0,United Kingdom
541702,581566,23404,HOME SWEET HOME BLACKBOARD,144,2011-12-09 11:50:00,3.26,18102.0,United Kingdom
541711,581567,21326,AGED GLASS SILVER T-LIGHT HOLDER,144,2011-12-09 11:56:00,0.55,16626.0,United Kingdom

In [71]:
quantity = df["Quantity"]

print(type(quantity))
print("Total:", quantity.sum())
print("Average:", quantity.mean())

<class 'pandas.Series'>
Total: 5176450
Average: 9.55224954743324