
# Data Cleaning properly isi Online Retail dataset par:
# Dataset load karna
# Missing values check
# isnull()
# notnull()
# isna()
# Missing values count
# Missing values percentage
# Duplicate rows check
# drop_duplicates()
# Missing values handle karna
# Data types check/change
# InvoiceDate ko datetime mein convert karna
# Invalid/negative values investigate karna
# Clean dataset ready karna

In [ ]:
import pandas as pd

In [2]:
import pandas as pd
df = pd.read_csv("Online Retail.csv")

In [3]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [4]:
# null values check karne ka liye
df.isnull().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [5]:
# yeh bataye ga dataset ma total kitne missing value hai
df.isnull().sum().sum()

np.int64(136534)

In [6]:
# Column-wise missing values check karne ka liye
df.isnull().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [7]:
# Missing Values ki Percentage nikalne ka formula
missing_percentage = (df.isnull().sum() / len(df)) * 100
missing_percentage

InvoiceNo       0.000000
StockCode       0.000000
Description     0.268311
Quantity        0.000000
InvoiceDate     0.000000
UnitPrice       0.000000
CustomerID     24.926694
Country         0.000000
dtype: float64

In [8]:
missing_data = pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Missing Percentage": (df.isnull().sum() / len(df)) * 100
})

missing_data

             Missing Values  Missing Percentage
InvoiceNo                 0            0.000000
StockCode                 0            0.000000
Description            1454            0.268311
Quantity                  0            0.000000
InvoiceDate               0            0.000000
UnitPrice                 0            0.000000
CustomerID           135080           24.926694
Country                   0            0.000000

In [9]:
# Duplicate Rows Check karne ka liye
df.duplicated().sum()

np.int64(5268)

In [10]:
df[df.duplicated()].head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
517,536409,21866,UNION JACK FLAG LUGGAGE TAG,1,2010-12-01 11:45:00,1.25,17908.0,United Kingdom
527,536409,22866,HAND WARMER SCOTTY DOG DESIGN,1,2010-12-01 11:45:00,2.10,17908.0,United Kingdom
537,536409,22900,SET 2 TEA TOWELS I LOVE LONDON,1,2010-12-01 11:45:00,2.95,17908.0,United Kingdom
539,536409,22111,SCOTTIE DOG HOT WATER BOTTLE,1,2010-12-01 11:45:00,4.95,17908.0,United Kingdom
555,536412,22327,ROUND SNACK BOXES SET OF 4 SKULLS,1,2010-12-01 11:49:00,2.95,17920.0,United Kingdom

In [11]:
# Agar tum complete duplicate rows ka count aur percentage ek saath dekhna chaho:
duplicate_count = df.duplicated().sum()
duplicate_percentage = (duplicate_count / len(df)) * 100

print("Duplicate Rows:", duplicate_count)
print("Duplicate Percentage:", duplicate_percentage)

Duplicate Rows: 5268
Duplicate Percentage: 0.9721189350979592

In [15]:
# drop_duplicates()
before = len(df)
# Ab duplicates remove karo:
df = df.drop_duplicates()
after = len(df)
print("Before:", before)
print("After:", after)
print("Removed:", before - after)
df.duplicated().sum()

Before: 536641
After: 536641
Removed: 0

np.int64(0)

In [16]:
# har column ka datatype check karne ka liye
df.dtypes

InvoiceNo          str
StockCode          str
Description        str
Quantity         int64
InvoiceDate        str
UnitPrice      float64
CustomerID     float64
Country            str
dtype: object

In [ ]:
# InvoiceDate ko datetime mein convert karna
# InvoiceDate abhi string hai. Date-related analysis ke liye ise proper datetime banana zaroori hai.
df["InvoiceDate"].head()
# ab datetime ma covert karne ka liye
df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"])
df["InvoiceDate"].dtype
# Datetime banne ke baad hum future mein easily:
# year kaliye
df["InvoiceDate"].dt.year
# month ka liye
df["InvoiceDate"].dt.month
# day ka liye
df["InvoiceDate"].dt.day
# hour ka liye
df["InvoiceDate"].dt.hour
# day name ka liye
df["InvoiceDate"].dt.day_name()

0         Wednesday
1         Wednesday
2         Wednesday
3         Wednesday
4         Wednesday
            ...
541904       Friday
541905       Friday
541906       Friday
541907       Friday
541908       Friday
Name: InvoiceDate, Length: 536641, dtype: str

In [21]:
df["InvoiceDate"].head()

0   2010-12-01 08:26:00
1   2010-12-01 08:26:00
2   2010-12-01 08:26:00
3   2010-12-01 08:26:00
4   2010-12-01 08:26:00
Name: InvoiceDate, dtype: datetime64[us]

In [25]:
# sab ko aik sath check karne  ka liye 
df["Year"] = df["InvoiceDate"].dt.year
df["Month"] = df["InvoiceDate"].dt.month
df["Day"] = df["InvoiceDate"].dt.day
df["Hour"] = df["InvoiceDate"].dt.hour

df[["InvoiceDate", "Year", "Month", "Day", "Hour"]].head()

          InvoiceDate  Year  Month  Day  Hour
0 2010-12-01 08:26:00  2010     12    1     8
1 2010-12-01 08:26:00  2010     12    1     8
2 2010-12-01 08:26:00  2010     12    1     8
3 2010-12-01 08:26:00  2010     12    1     8
4 2010-12-01 08:26:00  2010     12    1     8

In [28]:
# Invalid / Negative Values check.
# Online Retail data mein Quantity aur UnitPrice ko blindly clean nahi karna. Pehle check karenge ke negative values kitni hain.
# Negative Value
(df["Quantity"] < 0).sum()
# Unit Value
(df["UnitPrice"] < 0).sum()
# Zero unit Value
(df["UnitPrice"] == 0).sum()
df = df[df["Quantity"] > 0]

In [29]:
print("Negative Quantity:", (df["Quantity"] < 0).sum())
print("Negative UnitPrice:", (df["UnitPrice"] < 0).sum())
print("Zero UnitPrice:", (df["UnitPrice"] == 0).sum())

Negative Quantity: 0
Negative UnitPrice: 2
Zero UnitPrice: 1174

In [31]:
# Negative UnitPrice ki rows
df[df["UnitPrice"] < 0]
df[df["UnitPrice"] == 0].head(10)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Year,Month,Day,Hour
622,536414,22139,NaN,56,2010-12-01 11:52:00,0.0,NaN,United Kingdom,2010,12,1,11
1970,536545,21134,NaN,1,2010-12-01 14:32:00,0.0,NaN,United Kingdom,2010,12,1,14
1971,536546,22145,NaN,1,2010-12-01 14:33:00,0.0,NaN,United Kingdom,2010,12,1,14
1972,536547,37509,NaN,1,2010-12-01 14:33:00,0.0,NaN,United Kingdom,2010,12,1,14
1987,536549,85226A,NaN,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom,2010,12,1,14
1988,536550,85044,NaN,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom,2010,12,1,14
2024,536552,20950,NaN,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom,2010,12,1,14
2025,536553,37461,NaN,3,2010-12-01 14:35:00,0.0,NaN,United Kingdom,2010,12,1,14
2026,536554,84670,NaN,23,2010-12-01 14:35:00,0.0,NaN,United Kingdom,2010,12,1,14
4348,536765,84952C,NaN,19,2010-12-02 14:43:00,0.0,NaN,United Kingdom,2010,12,2,14

In [32]:
# Isse humein saare zero + negative price transactions ek jagah mil jayenge.
df[df["UnitPrice"] <= 0][
    ["InvoiceNo", "StockCode", "Description", "Quantity", "UnitPrice", "CustomerID"]
]

,InvoiceNo,StockCode,Description,Quantity,UnitPrice,CustomerID
622,536414,22139,NaN,56,0.0,NaN
1970,536545,21134,NaN,1,0.0,NaN
1971,536546,22145,NaN,1,0.0,NaN
1972,536547,37509,NaN,1,0.0,NaN
1987,536549,85226A,NaN,1,0.0,NaN
...,...,...,...,...,...,...
535334,581211,22142,check,14,0.0,NaN
536981,581234,72817,NaN,27,0.0,NaN
538504,581406,46000M,POLYESTER FILLER PAD 45x45cm,240,0.0,NaN
538505,581406,46000S,POLYESTER FILLER PAD 40x40cm,300,0.0,NaN
538554,581408,85175,NaN,20,0.0,NaN

In [ ]:
# is ma jo value 0 ka value hai wo pata lag jae gi
df[df["UnitPrice"] == 0][
    ["InvoiceNo", "StockCode", "Description", "Quantity", "UnitPrice", "CustomerID"]
].head(20)

,InvoiceNo,StockCode,Description,Quantity,UnitPrice,CustomerID
622,536414,22139,NaN,56,0.0,NaN
1970,536545,21134,NaN,1,0.0,NaN
1971,536546,22145,NaN,1,0.0,NaN
1972,536547,37509,NaN,1,0.0,NaN
1987,536549,85226A,NaN,1,0.0,NaN
1988,536550,85044,NaN,1,0.0,NaN
2024,536552,20950,NaN,1,0.0,NaN
2025,536553,37461,NaN,3,0.0,NaN
2026,536554,84670,NaN,23,0.0,NaN
4348,536765,84952C,NaN,19,0.0,NaN
6391,536941,22734,amazon,20,0.0,NaN
6392,536942,22139,amazon,15,0.0,NaN
7187,536995,35951,NaN,57,0.0,NaN
7191,536999,21421,NaN,110,0.0,NaN
7194,537002,21651,NaN,70,0.0,NaN
9302,537197,22841,ROUND CAKE TIN VINTAGE GREEN,1,0.0,12647.0
12008,537361,21777,NaN,5,0.0,NaN
13263,537430,85215,NaN,120,0.0,NaN
13959,537436,84270,NaN,7,0.0,NaN
13960,537437,90167,NaN,10,0.0,NaN

In [34]:
df[df["UnitPrice"] < 0][
    ["InvoiceNo", "StockCode", "Description", "Quantity", "UnitPrice", "CustomerID"]
].head(20)

       InvoiceNo StockCode      Description  Quantity  UnitPrice  CustomerID
299983   A563186         B  Adjust bad debt         1  -11062.06         NaN
299984   A563187         B  Adjust bad debt         1  -11062.06         NaN

In [35]:
# CustomerID missing values
# Tumhare data mein CustomerID ki 135,080 missing values (~24.93%) hain.
# Pehle check karte hain ke missing CustomerID wali transactions kitni hain:
df[df["CustomerID"].isna()].head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Year,Month,Day,Hour
622,536414,22139,NaN,56,2010-12-01 11:52:00,0.00,NaN,United Kingdom,2010,12,1,11
1443,536544,21773,DECORATIVE ROSE BATHROOM BOTTLE,1,2010-12-01 14:32:00,2.51,NaN,United Kingdom,2010,12,1,14
1444,536544,21774,DECORATIVE CATS BATHROOM BOTTLE,2,2010-12-01 14:32:00,2.51,NaN,United Kingdom,2010,12,1,14
1445,536544,21786,POLKADOT RAIN HAT,4,2010-12-01 14:32:00,0.85,NaN,United Kingdom,2010,12,1,14
1446,536544,21787,RAIN PONCHO RETROSPOT,2,2010-12-01 14:32:00,1.66,NaN,United Kingdom,2010,12,1,14

In [36]:
# total missing value check karne ka liye 
df["CustomerID"].isna().sum()

np.int64(133322)

In [37]:
# ab descripton i total missing values
df[df["Description"].isna()].head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Year,Month,Day,Hour
622,536414,22139,NaN,56,2010-12-01 11:52:00,0.0,NaN,United Kingdom,2010,12,1,11
1970,536545,21134,NaN,1,2010-12-01 14:32:00,0.0,NaN,United Kingdom,2010,12,1,14
1971,536546,22145,NaN,1,2010-12-01 14:33:00,0.0,NaN,United Kingdom,2010,12,1,14
1972,536547,37509,NaN,1,2010-12-01 14:33:00,0.0,NaN,United Kingdom,2010,12,1,14
1987,536549,85226A,NaN,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom,2010,12,1,14

In [38]:
# ab description aur customer id ki dekhi
df[df["CustomerID"].isna()].head()
df[df["Description"].isna()].head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Year,Month,Day,Hour
622,536414,22139,NaN,56,2010-12-01 11:52:00,0.0,NaN,United Kingdom,2010,12,1,11
1970,536545,21134,NaN,1,2010-12-01 14:32:00,0.0,NaN,United Kingdom,2010,12,1,14
1971,536546,22145,NaN,1,2010-12-01 14:33:00,0.0,NaN,United Kingdom,2010,12,1,14
1972,536547,37509,NaN,1,2010-12-01 14:33:00,0.0,NaN,United Kingdom,2010,12,1,14
1987,536549,85226A,NaN,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom,2010,12,1,14

In [40]:
# Description missing rows remove
df = df.dropna(subset=["Description"])
df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Year,Month,Day,Hour
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,2010,12,1,8
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,2010,12,1,8
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,2010,12,1,8
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,2010,12,1,8
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,2010,12,1,8
...,...,...,...,...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France,2011,12,9,12
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France,2011,12,9,12
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France,2011,12,9,12
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France,2011,12,9,12
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France,2011,12,9,12

In [41]:
# ab verify kare ka koi missing value hai toh nhi 
df["Description"].isna().sum()

np.int64(0)

In [42]:
# ab Customer ki missing check karke remove kare
df[df["CustomerID"].isna()].head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Year,Month,Day,Hour
1443,536544,21773,DECORATIVE ROSE BATHROOM BOTTLE,1,2010-12-01 14:32:00,2.51,NaN,United Kingdom,2010,12,1,14
1444,536544,21774,DECORATIVE CATS BATHROOM BOTTLE,2,2010-12-01 14:32:00,2.51,NaN,United Kingdom,2010,12,1,14
1445,536544,21786,POLKADOT RAIN HAT,4,2010-12-01 14:32:00,0.85,NaN,United Kingdom,2010,12,1,14
1446,536544,21787,RAIN PONCHO RETROSPOT,2,2010-12-01 14:32:00,1.66,NaN,United Kingdom,2010,12,1,14
1447,536544,21790,VINTAGE SNAP CARDS,9,2010-12-01 14:32:00,1.66,NaN,United Kingdom,2010,12,1,14

In [47]:
df = df.dropna(subset=["CustomerID"])
df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Year,Month,Day,Hour
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,2010,12,1,8
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,2010,12,1,8
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,2010,12,1,8
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,2010,12,1,8
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,2010,12,1,8
...,...,...,...,...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France,2011,12,9,12
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France,2011,12,9,12
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France,2011,12,9,12
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France,2011,12,9,12
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France,2011,12,9,12

In [48]:
# ab verify kare ka koi missing value hai toh nhi 
df["CustomerID"].isna().sum()

np.int64(0)

In [49]:
# overall missing value check karne ka liye
df.isnull().sum()

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
Year           0
Month          0
Day            0
Hour           0
dtype: int64

In [50]:
df.shape

(392732, 12)

In [51]:
df.dtypes

InvoiceNo                 str
StockCode                 str
Description               str
Quantity                int64
InvoiceDate    datetime64[us]
UnitPrice             float64
CustomerID            float64
Country                   str
Year                    int32
Month                   int32
Day                     int32
Hour                    int32
dtype: object

In [52]:
# ab Clean Dataset ko save kiya
df.to_csv("Online_Retail_Cleaned.csv", index=False)